### ISSUE TITLE
cling warning (pyexactreal)

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#33]
When I import pyexact real from Python I see the following warning
```
Warning in cling::IncrementalParser::CheckABICompatibility():
  Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20180125'
  Extraction of runtime standard library version was: '20190222'
In file included from input_line_20:1:
/opt/sage/sage-py3-gcc/local/include/e-antic/renfxx.h:288:32: warning: unknown warning group '-Wterminate', ignored [-Wunknown-warning-option]
#pragma GCC diagnostic ignored "-Wterminate"
```

**Comment by saraedum** [comment]
The second part is fixed by https://github.com/videlec/e-antic/pull/56.

The first part is odd. How did you install cppyy? Is this inside SageMath?

**Comment by saraedum** [comment]
Does not seem to be anything to worry about too much. The `cppyy` from `pypi` is a binary that was built against a newer c++ lib than what SageMath is using. If everything seems to work normally, I should probably add it to the README that this is expected.
