### ISSUE TITLE
C++ tests depend on google-test

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#46]
I understand that benchmarks depend on google-test but I don't understand why the tests themselves do... Since I do not have the google headers this is annoying. Of course I could install the google headers but shouldn't the tests be runnable without benchmarks?

BTW where this `benchmark/benchmark.h` is supposed to come from?

**Comment by videlec** [comment]
for benchmark:
- https://github.com/google/benchmark
- https://aur.archlinux.org/packages/benchmark/

**Comment by saraedum** [comment]
The tests use google-test. The benchmarks use google benchmark.
