### ISSUE TITLE
test suite error message misleading

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#62]
I have a failing test suite. Since the makefile is located in a subfolder the following summary is not not enough informative:
```
============================================================================
Testsuite summary for libexactreal 0.0.1
============================================================================
# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See test/test-suite.log
Please report to julian.rueth@fsfe.org
============================================================================
```
The log is not in `test/test-suite.log` (this is a relative path to the Makefile I believe).

**Comment by saraedum** [comment]
The log should be in `libexactreal/test/test-suite.log`.

**Comment by saraedum** [comment]
There isn't much we can do about this. That's just how automake works with nested Makefiles.

**Comment by videlec** [comment]
Imagine somebody clones the project and run `make check`. How she is supposed to find the `test-suite.log`?

It could have been worse. The header of the summary says "libexactreal". Though I am not sure it refers to the folder or some project name.

**Comment by saraedum** [comment]
To be honest, I got confused by this once before. I resorted to `find -name test-suite.log`. I think if you look at the surropnding `Entering directory` messages, you should be able to find the right place. But of course, people are usually ignoring such noise.

**Comment by saraedum** [comment]
I think we have to live with this. This is just how automake works.
