### ISSUE TITLE
arb in exact-real

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#63]
1. The source code of arb is now a submodule of `exact-real`. Should I expect arb to be build at the time I build `exact-real`? There is something apparently wrong as I got a test failure (the cereal arb related one) with a segmentation fault. Doing `make install` before `make check` does not change anything.
2. It would be nice to update the `.gitignore` of arb [gitignore.patch.txt](https://github.com/flatsurf/exact-real/files/3490294/gitignore.patch.txt) so that we don't see build related files when doing `git status` inside `exact-real`

**Comment by videlec** [comment]
and inside gdb I do not get segmentation fault :-(

**Comment by saraedum** [comment]
Arb is not being built. Just the bits that are the not-yet-released serialization. There's no conflict with the local arb (at least not until my patch has been merged and released.)

**Comment by saraedum** [comment]
2. True, will do.

**Comment by saraedum** [comment]
I'll have a look at what could be causing that segfault.

**Comment by saraedum** [comment]
Once my changes have been accepted into arb upstream https://github.com/fredrik-johansson/arb/pull/286, we should try whether you still get that segfault.

**Comment by saraedum** [comment]
Until then, I'll probably not fix 2 since a changed .gitignore would certainly not make it into arb.

**Comment by fredrik-johansson** [comment]
I don't have anything against putting everything and the kitchen sink in .gitignore.

**Comment by saraedum** [comment]
Oh, ok. Sure, then I'll add that too :)

**Comment by saraedum** [comment]
That kitchen sink is now https://github.com/fredrik-johansson/arb/pull/294.

**Comment by saraedum** [comment]
Moved the remaining bit to https://github.com/flatsurf/exact-real/issues/76.
