### ISSUE TITLE
failing test element.py

### ISSUE THREAD

**Issue by videlec** [flatsurf/exact-real#65]
At commit 8cda2fa I got a test failure. See [test-suite.log](https://github.com/flatsurf/exact-real/files/3613773/test-suite.log).

**Comment by saraedum** [comment]
I am getting rid of `boost_binary` with my latest changes for the SageMath interface. Let's try again once I've pushed them.

**Comment by saraedum** [comment]
Can you check again @videlec ?

**Comment by videlec** [comment]
It got worse [pyexactreal-test-suite.log](https://github.com/flatsurf/exact-real/files/3681264/pyexactreal-test-suite.log).

**Comment by saraedum** [comment]
I wouldn't call it worse really. The original problem is fixed. Now SageMath tests fail for you but these were not available then.

**Comment by saraedum** [comment]
https://github.com/flatsurf/exact-real/issues/71 is a followup.
